- name: "Ensure {{ service_cfg.directory }} and subdirectories exists"
  become: true
  file:
    path: "{{ (service_cfg.directory, item) | path_join }}"
    state: directory
    owner: "{{ service_cfg.owner }}"
    group: "{{ service_cfg.group }}"
    mode: "775"
  with_items: "{{ [''] + service_cfg.subdirs }}"
  tags: [ always ]